import Link from "next/link";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("/aviso-legal", "Aviso legal y límites del análisis", "Titular, finalidad educativa, riesgos, fuentes, propiedad intelectual y contacto de ABCM.");

export default function LegalPage() {
  return <main className="privacy-shell">
    <header className="privacy-header"><Link href="/">← ABCM</Link><span>28 septiembre 2026</span></header>
    <section className="privacy-intro"><span className="eyebrow">ABCM</span><h1>Aviso legal · Legal notice</h1><p>Información sobre este proyecto, sus fuentes y los límites de su análisis.</p></section>
    <div className="privacy-grid">
      <article className="privacy-language" lang="es">
        <h2>Información en español</h2>
        <section><h3>Titular y finalidad</h3><p>Jaime Ramsden de Frutos (JimBLogic) edita Austrian Business Cycle Monitor. Contacto: <a href="mailto:jrf91@pm.me">jrf91@pm.me</a>. Es un proyecto de aprendizaje y divulgación de macroeconomía, economía austriaca y Bitcoin, sin ánimo de lucro ni ingresos por este Site. Su contenido está dirigido al público adulto; no está diseñado para menores de la edad de consentimiento digital aplicable.</p><p>El Site no presta servicios de inversión, recibe órdenes, ejecuta operaciones, custodia fondos ni conecta carteras. No solicita pagos, datos de tarjetas, claves privadas ni datos de salud. No dispone de comentarios públicos, cuentas de visitantes ni subida de archivos.</p></section>
        <section><h3>Datos, opiniones y riesgos</h3><p>Las observaciones publicadas por las fuentes, los cálculos propios y las interpretaciones teóricas son elementos distintos. El enfoque austriaco es una perspectiva editorial, no un consenso científico ni una garantía predictiva. Las puntuaciones son experimentales: no son probabilidades de recesión ni señales para comprar, vender o mantener un activo.</p><p>Los datos pueden retrasarse, revisarse, ser incompletos o contener errores. Comprueba la fecha y procedencia de cada serie. Ni los escenarios ni los resultados históricos garantizan resultados futuros. Bitcoin y otros activos pueden sufrir pérdidas importantes, incluida la pérdida total del capital invertido. El Site no evalúa tu situación ni la idoneidad de una inversión.</p><p>Estos límites describen el servicio y no excluyen responsabilidades ni derechos que sean irrenunciables conforme a la ley.</p></section>
        <section><h3>Fuentes y propiedad intelectual</h3><p>Los enlaces a autores, organismos y proveedores identifican fuentes o referencias; no implican patrocinio, afiliación, aval ni autoría del modelo. Las explicaciones de ABCM no deben atribuirse a esos terceros.</p><p>El acceso público a una API, libro o serie no equivale a una licencia universal de reproducción. Los datos, marcas, publicaciones, tipografías y dependencias conservan sus respectivas condiciones. Consulta los términos del repositorio para el código y los de cada proveedor antes de reutilizar sus datos; no se concede aquí una licencia sobre contenido de terceros. Geist y Geist Mono se distribuyen con su <a href="/fonts/OFL.txt">licencia SIL Open Font License</a>. Las referencias bibliográficas enlazan a sus fuentes, sin alojar copias de los libros.</p><p>S&P 500 (S&P Dow Jones Indices), VIX (Cboe) y el diferencial Baa (Moody’s / Federal Reserve Bank of St. Louis) se utilizan para aprendizaje, estudio y análisis contextual, con sus fuentes y fechas. La finalidad educativa y no comercial no equivale por sí sola a una autorización ni a una declaración de que todo uso esté amparado por «fair use». Consulta la procedencia en cada indicador y la sección Fuentes del monitor. Por ejemplo, <a href="https://fred.stlouisfed.org/legal/" target="_blank" rel="noreferrer">FRED advierte sobre derechos de terceros</a>; atribuir una serie no sustituye los permisos que puedan exigirse.</p></section>
        <p><a href="https://fred.stlouisfed.org/series/SP500" target="_blank" rel="noreferrer">S&amp;P 500 · S&amp;P Dow Jones Indices / FRED</a> · <a href="https://fred.stlouisfed.org/series/VIXCLS" target="_blank" rel="noreferrer">VIX · Cboe / FRED</a> · <a href="https://fred.stlouisfed.org/series/BAA10Y" target="_blank" rel="noreferrer">Baa–10Y · Moody’s / St. Louis Fed</a></p><section><h3>Correcciones, derechos y denuncias</h3><p>Para comunicar un error, una posible vulneración de derechos o contenido inapropiado, escribe al contacto indicando la URL, el contenido y el motivo. No incluyas información sensible. El editor revisará la comunicación y corregirá o retirará el contenido cuando corresponda. También puedes usar el <a href="https://openai.com/form/report-content/" target="_blank" rel="noreferrer">formulario de denuncia de OpenAI</a>.</p><p>Consulta el tratamiento de datos y las opciones de borrado en <Link href="/privacidad">Privacidad</Link>.</p></section>
      </article>
      <article className="privacy-language" lang="en">
        <h2>Information in English</h2>
        <section><h3>Publisher and purpose</h3><p>Austrian Business Cycle Monitor is published by Jaime Ramsden de Frutos (JimBLogic). Contact: <a href="mailto:jrf91@pm.me">jrf91@pm.me</a>. It is a non-commercial learning resource on macroeconomics, Austrian economics and Bitcoin, with no revenue from this Site, intended for adults and not designed for children below the applicable age of digital consent.</p><p>The Site does not provide investment services, receive orders, execute trades, hold funds or connect wallets. It does not request payments, card details, private keys or health data. There are no public comments, visitor accounts or file uploads.</p></section>
        <section><h3>Data, opinions and risks</h3><p>Source observations, original calculations and theoretical interpretations are distinct. Austrian economics is an editorial perspective, not a scientific consensus or a predictive guarantee. Experimental scores are not recession probabilities or signals to buy, sell or hold an asset.</p><p>Data may be delayed, revised, incomplete or incorrect. Check each series’ date and provenance. Scenarios and past performance do not guarantee future results. Bitcoin and other assets can incur substantial losses, including total loss of invested capital. The Site does not assess your circumstances or investment suitability.</p><p>These limits describe the service and do not exclude non-waivable legal rights or liabilities.</p></section>
        <section><h3>Sources and intellectual property</h3><p>References to authors, institutions and providers identify sources; they do not imply sponsorship, affiliation, endorsement or authorship of the model. ABCM explanations should not be attributed to those third parties.</p><p>Public access to an API, book or series is not a universal reproduction licence. Data, trademarks, publications, fonts and dependencies remain subject to their respective terms. Consult repository terms for code and provider terms before reusing data. No third-party content licence is granted here. Geist and Geist Mono are distributed with their <a href="/fonts/OFL.txt">SIL Open Font License</a>. Bibliographic references link to sources without hosting copies of books.</p><p>S&P 500 (S&P Dow Jones Indices), VIX (Cboe) and the Baa spread (Moody’s / Federal Reserve Bank of St. Louis) are used for learning, study and contextual analysis, with sources and observation dates. Educational and non-commercial intent alone does not establish permission or mean that every use qualifies as fair use. Provenance appears in indicators and the monitor’s Sources section. For example, <a href="https://fred.stlouisfed.org/legal/" target="_blank" rel="noreferrer">FRED describes third-party rights</a>; attribution does not replace any required permissions.</p></section>
        <p><a href="https://fred.stlouisfed.org/series/SP500" target="_blank" rel="noreferrer">S&amp;P 500 · S&amp;P Dow Jones Indices / FRED</a> · <a href="https://fred.stlouisfed.org/series/VIXCLS" target="_blank" rel="noreferrer">VIX · Cboe / FRED</a> · <a href="https://fred.stlouisfed.org/series/BAA10Y" target="_blank" rel="noreferrer">Baa–10Y · Moody’s / St. Louis Fed</a></p><section><h3>Corrections, rights and reports</h3><p>Email the publisher to report an error, suspected rights infringement or inappropriate content, with the relevant URL, content and reason. Do not include sensitive information. Reports will be reviewed and content corrected or removed where appropriate. You can also use <a href="https://openai.com/form/report-content/" target="_blank" rel="noreferrer">OpenAI’s reporting form</a>.</p><p>Read <Link href="/privacidad">Privacy</Link> for data processing and local deletion options.</p></section>
      </article>
    </div>
  </main>;
}
