export type LibraryTrack = "bitcoin" | "cypherpunk" | "austrian" | "evidence";
export type LibraryLevel = "intro" | "intermediate" | "advanced";
export type LibraryItem = {
  track: LibraryTrack; level: LibraryLevel; kind: string; author: string; year: string;
  title: string; titleEs?: string; value: [string, string]; limit: [string, string]; url: string;
};

export const libraryItems: LibraryItem[] = [
  { track:"bitcoin",level:"intro",kind:"paper",author:"Satoshi Nakamoto",year:"2008",title:"Bitcoin: A Peer-to-Peer Electronic Cash System",titleEs:"Bitcoin: efectivo electrónico entre pares",value:["Primary specification of Bitcoin’s original problem, proof-of-work chain and incentives.","Especificación primaria del problema original, la cadena de prueba de trabajo y los incentivos."],limit:["Not a complete description of today’s implementation, governance or economics.","No describe por completo la implementación, gobernanza o economía actuales."],url:"https://bitcoin.org/en/bitcoin-paper" },
  { track:"bitcoin",level:"intermediate",kind:"archive",author:"Satoshi Nakamoto",year:"2008–2010",title:"The Complete Satoshi",titleEs:"Archivo completo de Satoshi",value:["Original emails, forum posts and code commentary contextualize design choices.","Correos, mensajes y comentarios de código originales contextualizan decisiones de diseño."],limit:["Historical statements are not consensus rules; running code is the operative reference.","Las declaraciones históricas no son reglas de consenso; el código ejecutado es la referencia."],url:"https://nakamotoinstitute.org/library/bitcoin/" },
  { track:"bitcoin",level:"intermediate",kind:"documentation",author:"Bitcoin Project",year:"Living",title:"Bitcoin Developer Guide",titleEs:"Guía para desarrolladores de Bitcoin",value:["Technical explanations of the chain, transactions, wallets, P2P network and mining.","Explicaciones técnicas de cadena, transacciones, wallets, red P2P y minería."],limit:["Verify consensus-sensitive details in Bitcoin Core.","Verifica en Bitcoin Core los detalles sensibles al consenso."],url:"https://developer.bitcoin.org/devguide/" },
  { track:"bitcoin",level:"advanced",kind:"documentation",author:"Bitcoin contributors",year:"Living",title:"Bitcoin Improvement Proposals",titleEs:"Propuestas de mejora de Bitcoin",value:["Public standards record for protocol, wallet and process proposals, with status and rationale.","Registro público de propuestas de protocolo, wallets y procesos, con estado y justificación."],limit:["A BIP is not proof of universal adoption or a consensus rule.","Un BIP no demuestra adopción universal ni que sea regla de consenso."],url:"https://github.com/bitcoin/bips" },
  { track:"bitcoin",level:"intermediate",kind:"book",author:"Andreas M. Antonopoulos",year:"Open source",title:"Mastering Bitcoin",value:["A code-oriented route from keys and transactions to scripts, wallets and network operation.","Ruta orientada al código desde claves y transacciones hasta scripts, wallets y red."],limit:["Use an edition compatible with current software behavior.","Usa una edición compatible con el software actual."],url:"https://github.com/bitcoinbook/bitcoinbook" },
  { track:"bitcoin",level:"advanced",kind:"documentation",author:"Bitcoin Optech",year:"Living",title:"Bitcoin Optech Topics",titleEs:"Temas técnicos de Bitcoin Optech",value:["Maintainer-focused explanations of scaling, privacy, fees and protocol engineering.","Explicaciones para desarrolladores sobre escalabilidad, privacidad, comisiones y protocolo."],limit:["Technical trade-offs depend on context and do not settle policy debates.","Los compromisos técnicos dependen del contexto y no zanjan debates de política."],url:"https://bitcoinops.org/en/topics/" },
  { track:"bitcoin",level:"intro",kind:"essay",author:"Lyn Alden",year:"2022",title:"What Is Money?",titleEs:"¿Qué es el dinero?",value:["Monetary history and settlement-layer framework connecting commodities, ledgers and Bitcoin.","Historia monetaria y capas de liquidación que conectan mercancías, registros y Bitcoin."],limit:["A documented analytical synthesis, not a neutral textbook.","Síntesis analítica documentada, no un manual neutral."],url:"https://www.lynalden.com/what-is-money/" },
  { track:"bitcoin",level:"intermediate",kind:"paper",author:"Saifedean Ammous",year:"2018",title:"Can cryptocurrencies fulfil the functions of money?",titleEs:"¿Pueden las criptomonedas cumplir las funciones del dinero?",value:["A peer-reviewed argument distinguishing Bitcoin from other digital assets.","Argumento revisado por pares que distingue Bitcoin de otros activos digitales."],limit:["Peer review validates publication process, not every conclusion.","La revisión por pares valida el proceso, no todas las conclusiones."],url:"https://doi.org/10.1016/j.qref.2018.05.010" },
  { track:"bitcoin",level:"intro",kind:"essay",author:"Parker Lewis",year:"Series",title:"Gradually, Then Suddenly",value:["Public series on monetary properties, incentives and Bitcoin’s competitive thesis.","Serie pública sobre propiedades monetarias, incentivos y la tesis competitiva de Bitcoin."],limit:["Advocacy should be contrasted with protocol documentation and opposing theories.","Su defensa debe contrastarse con documentación técnica y teorías opuestas."],url:"https://nakamotoinstitute.org/library/gradually-then-suddenly/" },
  { track:"cypherpunk",level:"intermediate",kind:"paper",author:"David Chaum",year:"1982",title:"Blind Signatures for Untraceable Payments",titleEs:"Firmas ciegas para pagos no rastreables",value:["Foundational cryptographic construction for privacy-preserving digital cash.","Construcción criptográfica fundacional del efectivo digital privado."],limit:["It still relies on an issuer and does not solve decentralized double spending.","Mantiene un emisor y no resuelve el doble gasto descentralizado."],url:"https://chaum.com/wp-content/uploads/2022/01/Chaum-blind-signatures.pdf" },
  { track:"cypherpunk",level:"intro",kind:"essay",author:"Eric Hughes",year:"1993",title:"A Cypherpunk’s Manifesto",titleEs:"Manifiesto cypherpunk",value:["Primary statement of privacy as selective disclosure and building working systems.","Declaración primaria de privacidad como revelación selectiva y construcción de sistemas."],limit:["A political-technical manifesto, not empirical proof that code solves every social problem.","Manifiesto político-técnico, no prueba de que el código resuelva todo problema social."],url:"https://nakamotoinstitute.org/library/cypherpunk-manifesto/" },
  { track:"cypherpunk",level:"intermediate",kind:"essay",author:"Timothy C. May",year:"1988",title:"The Crypto Anarchist Manifesto",titleEs:"Manifiesto criptoanarquista",value:["Historical primary source for radical expectations surrounding strong cryptography.","Fuente primaria de expectativas radicales en torno a la criptografía fuerte."],limit:["Contains ideology, predictions and acknowledged harms; read it historically, not devotionally.","Contiene ideología, predicciones y daños reconocidos; debe leerse históricamente."],url:"https://nakamotoinstitute.org/library/crypto-anarchist-manifesto/" },
  { track:"cypherpunk",level:"advanced",kind:"paper",author:"Haber & Stornetta",year:"1991",title:"How to Time-Stamp a Digital Document",titleEs:"Cómo sellar temporalmente un documento digital",value:["Research foundation for chaining timestamps so later alteration becomes detectable.","Base académica para encadenar sellos temporales y detectar alteraciones."],limit:["Timestamp chaining alone is not decentralized monetary consensus.","El encadenamiento temporal no es por sí solo consenso monetario."],url:"https://nakamotoinstitute.org/library/time-stamp-digital-document/" },
  { track:"cypherpunk",level:"advanced",kind:"paper",author:"Adam Back",year:"1997 / 2002",title:"Hashcash",value:["Primary proof-of-work cost-function documentation cited by Bitcoin.","Documentación primaria de prueba de trabajo citada por Bitcoin."],limit:["Hashcash lacked Bitcoin’s ledger, difficulty market and monetary incentives.","Hashcash no incluía registro, mercado de dificultad ni incentivos monetarios."],url:"https://nakamotoinstitute.org/library/hashcash/" },
  { track:"cypherpunk",level:"advanced",kind:"essay",author:"Wei Dai",year:"1998",title:"b-money",value:["Original proposal for pseudonymous money using computational work and distributed accounting.","Propuesta original de dinero seudónimo con trabajo computacional y contabilidad distribuida."],limit:["It remained a proposal and left coordination questions unresolved.","Permaneció como propuesta y dejó cuestiones de coordinación abiertas."],url:"https://nakamotoinstitute.org/library/b-money/" },
  { track:"cypherpunk",level:"advanced",kind:"essay",author:"Nick Szabo",year:"2005",title:"Bit Gold",value:["Precursor design linking costly computation, timestamped ownership and digital scarcity.","Diseño precursor que une cálculo costoso, propiedad sellada y escasez digital."],limit:["It was not deployed as specified and did not solve consensus like Bitcoin.","No se desplegó como fue descrito ni resolvía el consenso como Bitcoin."],url:"https://nakamotoinstitute.org/library/bit-gold/" },
  { track:"cypherpunk",level:"advanced",kind:"archive",author:"Hal Finney",year:"2004",title:"Reusable Proofs of Work",titleEs:"Pruebas de trabajo reutilizables",value:["Original RPOW archive shows a working step between Hashcash and Bitcoin.","El archivo RPOW muestra un paso funcional entre Hashcash y Bitcoin."],limit:["RPOW depended on trusted hardware and a server.","RPOW dependía de hardware confiable y un servidor."],url:"https://nakamotoinstitute.org/finney/rpow/" },
  { track:"austrian",level:"intro",kind:"book",author:"Carl Menger",year:"1892",title:"On the Origins of Money",titleEs:"Sobre el origen del dinero",value:["Classic market-emergence account of money through differences in saleability.","Explicación clásica del surgimiento del dinero por diferencias de vendibilidad."],limit:["Legal, institutional and anthropological evidence also matters.","También importa la evidencia legal, institucional y antropológica."],url:"https://mises.org/library/book/origins-money" },
  { track:"austrian",level:"advanced",kind:"book",author:"Ludwig von Mises",year:"1949",title:"Human Action",titleEs:"La acción humana",value:["Systematic statement of praxeology, value, calculation, money and market process.","Exposición sistemática de praxeología, valor, cálculo, dinero y proceso de mercado."],limit:["A theoretical treatise with explicit methodology, not an empirical macro handbook.","Tratado teórico con metodología explícita, no manual macro empírico."],url:"https://mises.org/library/book/human-action" },
  { track:"austrian",level:"advanced",kind:"book",author:"Ludwig von Mises",year:"1912",title:"The Theory of Money and Credit",titleEs:"La teoría del dinero y del crédito",value:["Integrates marginal value, money, fiduciary media and an early cycle theory.","Integra valor marginal, dinero, medios fiduciarios y una teoría temprana del ciclo."],limit:["Its institutional setting predates modern central banking.","Su marco institucional precede a la banca central moderna."],url:"https://mises.org/library/book/theory-money-and-credit" },
  { track:"austrian",level:"intermediate",kind:"essay",author:"F. A. Hayek",year:"1945",title:"The Use of Knowledge in Society",titleEs:"El uso del conocimiento en la sociedad",value:["Explains prices as coordination signals for dispersed and often tacit knowledge.","Explica los precios como señales para conocimiento disperso y tácito."],limit:["It does not claim every market price is efficient or just.","No afirma que todo precio de mercado sea eficiente o justo."],url:"https://oll.libertyfund.org/titles/hayek-the-use-of-knowledge-in-society-1945" },
  { track:"austrian",level:"advanced",kind:"book",author:"F. A. Hayek",year:"1929",title:"Monetary Theory and the Trade Cycle",titleEs:"Teoría monetaria y ciclo económico",value:["Primary development of the monetary and capital-based Austrian cycle mechanism.","Desarrollo primario del mecanismo monetario y de capital del ciclo austriaco."],limit:["The mechanism is debated and difficult to identify empirically.","El mecanismo es debatido y difícil de identificar empíricamente."],url:"https://mises.org/library/book/monetary-theory-and-trade-cycle" },
  { track:"austrian",level:"intermediate",kind:"book",author:"Israel M. Kirzner",year:"1973",title:"Competition and Entrepreneurship",titleEs:"Competencia y función empresarial",value:["Competition as discovery and entrepreneurship as alertness to opportunities.","Competencia como descubrimiento y función empresarial como alerta."],limit:["A process theory, not a mechanical replacement for every equilibrium model.","Teoría de proceso, no sustituto mecánico de todo modelo de equilibrio."],url:"https://mises.org/library/book/competition-and-entrepreneurship" },
  { track:"austrian",level:"advanced",kind:"book",author:"Murray N. Rothbard",year:"1962",title:"Man, Economy, and State",titleEs:"El hombre, la economía y el Estado",value:["Systematic development of Austrian price, production and intervention theory.","Desarrollo sistemático de precios, producción e intervención."],limit:["Separate economic analysis from normative political conclusions.","Separa análisis económico de conclusiones políticas normativas."],url:"https://mises.org/library/book/man-economy-and-state-power-and-market" },
  { track:"evidence",level:"advanced",kind:"paper",author:"Francis Bismans & Christelle Mougeot",year:"2009",title:"Austrian business cycle theory: Empirical evidence",titleEs:"Teoría austriaca del ciclo: evidencia empírica",value:["Panel-data research reporting relationships consistent with some ABCT predictions.","Investigación con datos de panel que encuentra relaciones compatibles con algunas predicciones de la ABCT."],limit:["Predicted relationships do not uniquely identify Austrian causality.","Las relaciones predichas no identifican de forma única la causalidad austriaca."],url:"https://www.econbiz.de/10005029378" },
  { track:"evidence",level:"advanced",kind:"paper",author:"Alonso-Neira, Bagus & Romero-Ania",year:"2019",title:"An empirical illustration of ABCT: US 1988–2010",titleEs:"Ilustración empírica de la ABCT: EE. UU. 1988–2010",value:["Connects the theory to U.S. credit, production and crisis data.","Conecta la teoría con datos estadounidenses de crédito, producción y crisis."],limit:["A coherent illustration does not exclude rival explanations.","Una ilustración coherente no excluye explicaciones rivales."],url:"https://repositorio.unam.mx/contenidos/46304" },
  { track:"evidence",level:"advanced",kind:"paper",author:"Elfving & Lindén · Lund University",year:"2011",title:"Analysis of US Sectoral Business Cycles",titleEs:"Análisis de ciclos sectoriales de Estados Unidos",value:["Finds some supportive patterns but insufficient robust evidence overall.","Encuentra algunos patrones favorables, pero evidencia robusta insuficiente."],limit:["A master’s thesis is useful counterevidence, not a final verdict.","Una tesis de máster aporta contraste, no un veredicto definitivo."],url:"https://www.lunduniversity.lu.se/publication/1970938" },
  { track:"evidence",level:"advanced",kind:"paper",author:"Olga Peniaz",year:"2018",title:"Minsky’s Financial Instability Hypothesis vs. ABCT",titleEs:"Hipótesis de inestabilidad de Minsky frente a ABCT",value:["Compares two heterodox interpretations of the 2008 crisis.","Compara dos interpretaciones heterodoxas de la crisis de 2008."],limit:["Comparison clarifies assumptions; it does not prove universal superiority.","La comparación aclara supuestos; no prueba superioridad universal."],url:"https://doi.org/10.52195/pm.v15i1.64" },
];
